language: generic

sudo: enabled

services:
    - docker

before_install:
    - docker pull rindeal/gentoo-overlay-testing:latest

script:
    - PUBLIC_DIR=`mktemp -d --suffix=".PUBLIC"`
    - docker run -v `pwd`:/repo:r -v $PUBLIC_DIR:/public:rw rindeal/gentoo-overlay-testing:latest /bin/bash /repo/travis.sh

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: false
    on:
        branch: master
    local-dir: $PUBLIC_DIR
    target-branch: gh-pages
    email: deploy@travis-ci.org
    name: Travis CI Deployment Bot
    verbose: true
