language: python

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7

#sudo: enabled

#services:
#    - docker

#before_install:
#    - docker pull sabayon/base-amd64

script:
    - gcc-7 -### -E - -march=native 2>&1 | sed -r '/cc1/!d;s/(")|(^.* - )|( -mno-[^\ ]+)//g'
    - false
#    - PUBLIC_DIR=`mktemp -d --suffix=".PUBLIC"`
#    - docker run -v `pwd`:/repo:rw -v $PUBLIC_DIR:/public:rw sabayon/base-amd64 /bin/bash /repo/travis.sh

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: false
    on:
      branch: master
    local-dir: $PUBLIC_DIR
    target-branch: gh-pages
    email: deploy@travis-ci.org
    name: Travis CI Deployment Bot
    verbose: true
